# echo "NTP=ntp.nict.jp" | sudo tee -a /etc/systemd/timesyncd.conf
# sudo systemctl restart systemd-timesyncd
- name: edit /etc/systemd/timesyncd.conf
  blockinfile:
    dest: /etc/systemd/timesyncd.conf
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      NTP=ntp.nict.jp
- name: Restart systemd-timesyncd
  ignore_errors: True
  systemd:
    name: systemd-timesyncd
    state: restarted
