- name: check rustup installed
  stat:
    path: ~/.cargo
  register: check_rustup
  become: no
- block:
    - name: download rustup
      become: no
      uri:
        url: https://sh.rustup.rs
        return_content: yes
      register: rustup
    - name: run rustup
      become: no
      shell:
        cmd: sh -s -- -y
        stdin: "{{ rustup.content }}"
  when:
    - not check_rustup.stat.exists
- name: rustup self update
  become: no
  shell: ~/.cargo/bin/rustup self update
- name: rustup update
  become: no
  shell: ~/.cargo/bin/rustup update
- name: add PATH ~/.zshrc
  become: no
  blockinfile:
    dest: ~/.zshrc
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK rust"
    content: |
      export PATH="$HOME/.cargo/bin:$PATH"
- name: add PATH ~/.config/fish/config.fish
  become: no
  blockinfile:
    dest: ~/.config/fish/config.fish
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK rust"
    content: |
      set -x PATH ~/.cargo/bin $PATH
- name: add PATH ~/.bashrc
  become: no
  blockinfile:
    dest: ~/.bashrc
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK rust"
    content: |
      export PATH="$HOME/.cargo/bin:$PATH"

- name: install fd-find
  become: no
  shell: ~/.cargo/bin/cargo install fd-find

- name: check exa installed
  stat:
    path: /usr/local/bin/exa
  register: check_exa
  become: no
- block:
    - name: download exa
      get_url:
        url: https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip
        dest: /tmp/exa.zip
    - name: unzip exa
      become: no
      shell: unzip -o /tmp/exa.zip -d /tmp/exa
    - name: copy exa
      shell: cp /tmp/exa/bin/exa /usr/local/bin/
  when:
    - not check_exa.stat.exists

- name: check ripgrep installed
  stat:
    path: /usr/bin/rg
  register: check_ripgrep
  become: no
- block:
    - name: download ripgrep
      get_url:
        url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
        dest: /tmp/ripgrep.deb
    - name: install ripgrep
      shell: dpkg -i /tmp/ripgrep.deb
  when:
    - not check_ripgrep.stat.exists

- name: check bat installed
  stat:
    path: /usr/bin/bat
  register: check_bat
  become: no
- block:
    - name: download bat
      get_url:
        url: https://github.com/sharkdp/bat/releases/download/v0.21.0/bat_0.21.0_amd64.deb
        dest: /tmp/bat.deb
    - name: install bat
      shell: dpkg -i /tmp/bat.deb
  when:
    - not check_bat.stat.exists
