- name: ppa:fish-shell
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
- name: apt update
  apt:
    update_cache: yes
- name: "apt install fish"
  apt:
    pkg:
      - fish
- name: edit ~/.config/fish/config.fish
  become: no
  blockinfile:
    dest: ~/.config/fish/config.fish
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK fish"
    content: |
      # ======================================================================== #
      # Fish shell
      # ======================================================================== #

      function fish_greeting
      end

      set -g theme_powerline_fonts no
      set -g theme_nerd_fonts yes
      set -g theme_display_date no
      set -g theme_color_scheme dracula

      # ======================================================================== #
      # Customized command
      # ======================================================================== #

      function cd
        builtin cd $argv
        ls
      end

      # https://github.com/ogham/exa
      alias ls 'exa -lg --octal-permissions --time-style long-iso --icons'
      alias l 'exa -lg --octal-permissions --time-style long-iso --icons'
      alias la 'exa -lag --octal-permissions --time-style long-iso --icons'
      function lt
        if count $argv > /dev/null
          exa -lT --git --git-ignore --icons --time-style=long-iso -L=$argv
        else
          exa -lT --git --git-ignore --icons --time-style=long-iso -L=2
        end
      end

      # https://github.com/sharkdp/bat
      # bat --list-themes
      alias c 'bat --theme="OneHalfDark"'

      # https://github.com/BurntSushi/ripgrep
      alias gr 'rg'
      alias grl 'rg -l'

      # https://github.com/sharkdp/fd
      alias f 'fd'
      alias rmds 'fd -IH ".DS_Store" | xargs rm'
      alias cleanc 'fd ".*.c" | xargs clang-format -style=Google -i'
      alias cleanmd 'fd ".*.md" | xargs prettier --write'
      alias cleanjson 'fd ".*.json" | xargs prettier --write'
      alias cleanyml 'fd ".*.yml" | xargs prettier --write'
      alias cleancss 'fd ".*.css" -E ".*min.css" | xargs prettier --write'
      alias cleanjs 'fd ".*.js" -E ".*min.js" | xargs prettier --write'
      alias cleanpy 'fd ".*.py" | xargs black'
      alias cleansh 'fd ".*.sh" | xargs shfmt -i 2 -w'
      alias cleanhtml 'fd ".*.html" -E ".*min.html" | xargs js-beautify -I -r -n -s 2 --no-preserve-newlines'

      # ======================================================================== #
      # Shorthand command
      # ======================================================================== #

      alias vm 'cd ~/vm'

      alias ] 'cd ../'
      alias rmr 'rm -rf'
      alias cl 'clear'
      alias ncf 'nano ~/.config/fish/config.fish'

      alias up 'sudo apt update ; sudo apt upgrade -y'

      # Git
      alias g 'git'
      alias gl 'git pull'
      alias ga 'git add --all'
      alias gc 'git commit -m'
      alias gp 'git push origin (git_current_branch)'
      alias commit 'git add . ; git commit -m "commit" ; git push origin main'

      # Vagrant
      alias v 'vagrant'
      alias vup 'vagrant up'
      alias vssh 'vagrant ssh'
      alias vstat 'vagrant status'
      alias vdest 'vagrant destroy -f'
      alias vhalt 'vagrant halt'
      alias vrelo 'vagrant reload'
- name: install fisher
  shell: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
  become: no
  args:
    executable: /usr/bin/fish
- name: install fisher plugin
  shell: fisher install oh-my-fish/theme-bobthefish edc/bass jethrokuan/z
  become: no
  args:
    executable: /usr/bin/fish
- name: define whoami
  shell: whoami
  become: no
  register: whoami
- name: chsh -s /usr/bin/fish
  user:
    name: "{{ whoami.stdout }}"
    shell: /usr/bin/fish
