- name: dpkg --add-architecture i386
  shell: dpkg --add-architecture i386
- name: apt update
  apt:
    update_cache: yes
- name: apt install package
  apt:
    pkg:
      - gcc
      - gcc-multilib
      - g++-multilib
      - clang
      - gdb
      - gdb-multiarch
      - qemu-user-binfmt
- name: check gdb_dir
  stat:
    path: ~/gdb-peda-pwndbg-gef
  register: gdb_dir
  become: no
- block:
    - name: git clone gdb-peda-pwndbg-gef
      become: no
      shell: git clone -depth 1 https://github.com/apogiatzis/gdb-peda-pwndbg-gef.git ~/gdb-peda-pwndbg-gef
    - name: install gdb-peda-pwndbg-gef
      become: no
      shell: bash ./install.sh
      args:
        chdir: ~/gdb-peda-pwndbg-gef
  when:
    - not gdb_dir.stat.exists
- name: edit ~/.config/fish/config.fish
  become: no
  blockinfile:
    dest: ~/.config/fish/config.fish
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK pwn"
    content: |
      # https://github.com/Gallopsled/pwntools
      function exploit
        pwn template --host $argv[1] --port $argv[2] $argv[3] > exploit.py | black exploit.py
      end
