- name: download netdata
  uri:
    url: https://my-netdata.io/kickstart.sh
    return_content: yes
  register: netdata
- name: install netdata
  shell:
    cmd: bash -s -- --non-interactive
    stdin: "{{ netdata.content }}"
- name: systemctl enable netdata
  shell: systemctl enable netdata
- name: systemctl start netdata
  shell: systemctl start netdata
- name: open netdata
  shell: sed -i.bk -e 's/bind to = localhost/bind to = 0.0.0.0/g' /etc/netdata/netdata.conf
