- name: check docker installed
  shell: "which docker"
  register: check_docker
  failed_when: check_docker.rc not in [0,1]
- block:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download and install Docker GPG key
      shell: |
        curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg

    - name: Set permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: "0644"

    - name: Define lsb_release
      shell: "lsb_release -cs"
      ignore_errors: True
      register: lsb_release

    - name: Add Docker repository to sources.list.d
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
        create: true

    - name: Update package cache again
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-ce-rootless-extras
          - docker-buildx-plugin
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Define whoami
      shell: "whoami"
      become: false
      ignore_errors: True
      register: whoami

    - name: Usermod docker
      shell: "usermod -aG docker {{ whoami.stdout }}"

    - name: Restart docker service
      systemd:
        name: docker.service
        state: restarted
  when: check_docker.rc == 1

- name: edit ~/.bashrc
  become: false
  blockinfile:
    dest: ~/.bashrc
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK docker"
    content: |
      # Docker
      alias d='docker'
      alias dps='docker ps'
      alias dpsa='docker ps -a'
      alias dsa='docker start'
      alias dso='docker stop'
      alias drm='docker rm'
      alias drmi='docker rmi'
      alias dex='docker exec -it'
      alias di='docker images | sort -k6 -h'
      alias dip='docker image prune -f'
      alias dvp='docker volume prune -f'
      # Docker Compose
      alias dc='docker compose'
      alias dcb='docker compose build'
      alias dcu='docker compose up'
      alias dcup='docker compose up -d'
      alias dcso='docker compose stop'
      alias dcrm='docker compose rm -f'
      alias dcps='docker compose ps'
      alias dcex='docker compose exec'
- name: edit ~/.zshrc
  become: false
  blockinfile:
    dest: ~/.zshrc
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK docker"
    content: |
      # Docker
      alias d='docker'
      alias dps='docker ps'
      alias dpsa='docker ps -a'
      alias dsa='docker start'
      alias dso='docker stop'
      alias drm='docker rm'
      alias drmi='docker rmi'
      alias dex='docker exec -it'
      alias di='docker images | sort -k6 -h'
      alias dip='docker image prune -f'
      alias dvp='docker volume prune -f'
      # Docker Compose
      alias dc='docker compose'
      alias dcb='docker compose build'
      alias dcu='docker compose up'
      alias dcup='docker compose up -d'
      alias dcso='docker compose stop'
      alias dcrm='docker compose rm -f'
      alias dcps='docker compose ps'
      alias dcex='docker compose exec'
- name: edit ~/.config/fish/config.fish
  become: false
  blockinfile:
    dest: ~/.config/fish/config.fish
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK docker"
    content: |
      # Docker
      alias d 'docker'
      alias dps 'docker ps'
      alias dpsa 'docker ps -a'
      alias dsa 'docker start'
      alias dso 'docker stop'
      alias drm 'docker rm'
      alias drmi 'docker rmi'
      alias dex 'docker exec -it'
      alias di 'docker images | sort -k6 -h'
      alias dip 'docker image prune -f'
      alias dvp 'docker volume prune -f'
      # Docker Compose
      alias dc 'docker compose'
      alias dcb 'docker compose build'
      alias dcu 'docker compose up'
      alias dcup 'docker compose up -d'
      alias dcso 'docker compose stop'
      alias dcrm 'docker compose rm -f'
      alias dcps 'docker compose ps'
      alias dcex 'docker compose exec'
