- name: check eza installed
  stat:
    path: /usr/local/bin/eza
  register: check_eza
  become: false
- block:
    # https://github.com/eza-community/eza
    - name: download eza
      get_url:
        url: https://github.com/eza-community/eza/releases/download/v0.18.4/eza_x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/eza.tar.gz
    - name: unzip eza
      become: false
      shell: tar -zxvf /tmp/eza.tar.gz -C /tmp
    - name: copy eza
      shell: cp /tmp/eza /usr/local/bin/
  when:
    - not check_eza.stat.exists

- name: check ripgrep installed
  stat:
    path: /usr/bin/rg
  register: check_ripgrep
  become: false
- block:
    # https://github.com/BurntSushi/ripgrep
    - name: download ripgrep
      get_url:
        url: https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-x86_64-unknown-linux-musl.tar.gz
        dest: /tmp/ripgrep.tar.gz
    - name: unzip ripgrep
      become: false
      shell: tar -zxvf /tmp/ripgrep.tar.gz -C /tmp
    - name: copy ripgrep
      shell: cp /tmp/ripgrep-14.1.0-x86_64-unknown-linux-musl/rg /usr/local/bin/
  when:
    - not check_ripgrep.stat.exists

- name: check bat installed
  stat:
    path: /usr/bin/bat
  register: check_bat
  become: false
- block:
    # https://github.com/sharkdp/bat
    - name: download bat
      get_url:
        url: https://github.com/sharkdp/bat/releases/download/v0.24.0/bat_0.24.0_amd64.deb
        dest: /tmp/bat.deb
    - name: install bat
      shell: dpkg -i /tmp/bat.deb
  when:
    - not check_bat.stat.exists

- name: check fd installed
  stat:
    path: /usr/bin/fd
  register: check_fd
  become: false
- block:
    # https://github.com/sharkdp/fd
    - name: download fd
      get_url:
        url: https://github.com/sharkdp/fd/releases/download/v9.0.0/fd-musl_9.0.0_amd64.deb
        dest: /tmp/fd.deb
    - name: install fd
      shell: dpkg -i /tmp/fd.deb
  when:
    - not check_fd.stat.exists

- name: apt update
  apt:
    update_cache: yes
- name: apt install package
  apt:
    pkg:
      - fzf

- name: check devbox installed
  stat:
    path: /usr/local/bin/devbox
  register: check_devbox
  become: false
- block:
    # https://github.com/jetpack-io/devbox
    - name: download devbox
      uri:
        url: https://get.jetpack.io/devbox
        return_content: yes
      register: devbox
    - name: install devbox
      shell:
        cmd: bash -s -- -f
        stdin: "{{ devbox.content }}"
      become: false
  when:
    - not check_devbox.stat.exists
