- name: check exa installed
  stat:
    path: /usr/local/bin/exa
  register: check_exa
  become: no
- block:
    - name: download exa
      get_url:
        url: https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip
        dest: /tmp/exa.zip
    - name: unzip exa
      become: no
      shell: unzip -o /tmp/exa.zip -d /tmp/exa
    - name: copy exa
      shell: cp /tmp/exa/bin/exa /usr/local/bin/
  when:
    - not check_exa.stat.exists

- name: check ripgrep installed
  stat:
    path: /usr/bin/rg
  register: check_ripgrep
  become: no
- block:
    - name: download ripgrep
      get_url:
        url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
        dest: /tmp/ripgrep.deb
    - name: install ripgrep
      shell: dpkg -i /tmp/ripgrep.deb
  when:
    - not check_ripgrep.stat.exists

- name: check bat installed
  stat:
    path: /usr/bin/bat
  register: check_bat
  become: no
- block:
    - name: download bat
      get_url:
        url: https://github.com/sharkdp/bat/releases/download/v0.22.1/bat_0.22.1_amd64.deb
        dest: /tmp/bat.deb
    - name: install bat
      shell: dpkg -i /tmp/bat.deb
  when:
    - not check_bat.stat.exists

- name: check fd installed
  stat:
    path: /usr/bin/fd
  register: check_fd
  become: no
- block:
    - name: download fd
      get_url:
        url: https://github.com/sharkdp/fd/releases/download/v8.6.0/fd_8.6.0_amd64.deb
        dest: /tmp/fd.deb
    - name: install fd
      shell: dpkg -i /tmp/fd.deb
  when:
    - not check_fd.stat.exists

- name: check fzf cloned
  stat:
    path: ~/.fzf
  register: check_fzf
  become: no
- block:
    - name: git clone
      shell: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      become: no
    - name: install fzf
      shell: bash ~/.fzf/install --all
      become: no
  when:
    - not check_fzf.stat.exists
